// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Comment is the predicate function for comment builders.
type Comment func(*sql.Selector)

// Product is the predicate function for product builders.
type Product func(*sql.Selector)

// Tag is the predicate function for tag builders.
type Tag func(*sql.Selector)
