// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"geekstudy.example/go/4week-engineering/mall/internal/biz"
	"geekstudy.example/go/4week-engineering/mall/internal/conf"
	"geekstudy.example/go/4week-engineering/mall/internal/data"
	"geekstudy.example/go/4week-engineering/mall/internal/server"
	"geekstudy.example/go/4week-engineering/mall/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

func initApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	productRepo := data.NewProductRepo(dataData, logger)
	productUsecase := biz.NewProductUsecase(productRepo, logger)
	productService := service.NewProductService(productUsecase, logger)
	httpServer := server.NewHTTPServer(confServer, logger, productService)
	grpcServer := server.NewGRPCServer(confServer, logger, productService)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
